"""Generate packaging/version_info.txt from rebind.__version__, reproducibly.

The exe's Win32 version resource (Company/Product/File version, shown in Explorer's Properties
dialog) previously lived in a static, hand-maintained file that had to be bumped in lockstep with
`pyproject.toml` and `rebind.iss` -- and silently didn't, for every release after the first (it
sat at 0.0.1.0 through 0.2.0-0.4.0). Generating it here, called from `rebind.spec` before every
build, makes `rebind.__version__` the single source of truth PyInstaller's `version=` reads from.

    uv run python packaging/make_version_info.py

Also callable directly from rebind.spec: `import make_version_info; make_version_info.write()`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = Path(__file__).resolve().parent / "version_info.txt"

_TEMPLATE = """\
# Win32 version resource for rebind.exe, consumed by PyInstaller (`version=` on EXE()).
#
# GENERATED by packaging/make_version_info.py from rebind.__version__ -- do not edit by hand, and
# do not hand-maintain a version number here again (it drifted silently for four releases before
# this became a generator: stuck at 0.0.1.0 through 0.2.0-0.4.0). Regenerate with:
#     uv run python packaging/make_version_info.py
#
# Why this file exists at all: a PyInstaller-built exe has NO version resource unless one is
# supplied, and an executable with entirely empty metadata is a well-known antivirus heuristic
# trigger. Rebind's binary already looks alarming to a scanner without help -- it is unsigned,
# ~80 MB, packed by PyInstaller, ships native DLLs, and opens a local network listener on startup.
# Blank Company/Product/Description fields on top of that is the profile of something a
# managed-machine AV or an ASR rule declines to run, and Rebind's users are librarians on exactly
# such machines. Metadata is not a fix for being unsigned, but it removes one free strike.
#
# It is also a prerequisite for free open-source code signing via the SignPath Foundation, which
# requires product name and version attributes to be set consistently across all signed binaries.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple4},
    prodvers={tuple4},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',  # US English, Unicode
        [
          StringStruct('CompanyName', 'Thomas Scharff'),
          StringStruct('FileDescription', 'Rebind - accessible PDF remediation'),
          StringStruct('FileVersion', '{dotted}'),
          StringStruct('InternalName', 'rebind'),
          StringStruct('LegalCopyright', 'Copyright (c) Thomas Scharff. MIT License.'),
          StringStruct('OriginalFilename', 'rebind.exe'),
          StringStruct('ProductName', 'Rebind'),
          StringStruct('ProductVersion', '{dotted}'),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [0x409, 1200])]),
  ],
)
"""


def _rebind_version() -> str:
    """Read `__version__` straight from source (don't import rebind: this runs from inside
    PyInstaller's spec execution, before the frozen environment exists)."""
    init_py = (REPO_ROOT / "src" / "rebind" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', init_py)
    if not match:
        sys.exit("Could not find __version__ in src/rebind/__init__.py")
    return match.group(1)


def write() -> str:
    """Write version_info.txt for the current rebind.__version__. Returns the version string."""
    version = _rebind_version()
    parts = [int(p) for p in version.split(".")]
    while len(parts) < 4:
        parts.append(0)
    tuple4 = tuple(parts[:4])
    OUTPUT.write_text(_TEMPLATE.format(tuple4=tuple4, dotted=version), encoding="utf-8")
    return version


if __name__ == "__main__":
    v = write()
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} for version {v}")
