[Setup]
; Fixed, stable GUID identifying "Rebind" across all versions -- Inno Setup uses AppId (not
; AppName) to recognize an existing install for upgrade/uninstall purposes. Without an
; explicit AppId, Inno Setup derives one from AppName, which is fragile (a rename would orphan
; every existing install); generated once with `uv run python -c "import uuid; print(uuid.uuid4())"`
; and must never change between releases.
AppId={{11732952-84C2-467D-9E8D-5263D9A81C11}
AppName=Rebind
AppVersion=0.8.0
AppPublisher=Thomas Scharff
DefaultDirName={autopf}\Rebind
DefaultGroupName=Rebind
OutputBaseFilename=rebind-setup
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
; The click-through gate is Rebind's OWN license (MIT) -- what every normal installer shows, not
; the third-party notices. The bundle does vendor third-party components under LGPL/MIT/FTL/
; Apache-2.0/etc (the frozen Python dependency closure: the OCR engine, onnxruntime, opencv,
; pypdfium2, numpy, ... and the bundled OCR models), and those licenses' obligations are discharged
; by *installing* their texts where they remain available (the [Files] entry below, into
; {app}\licenses), not by forcing an interactive "I accept" click-through for code the user never
; directly interacts with -- no mainstream installer does that, and it was a mistake here (an
; earlier revision pointed LicenseFile at LICENSE-THIRD-PARTY.txt instead of this). Generated by
; scripts/license_inventory.py, which fails if any bundled Python distribution has no license text.
LicenseFile=..\LICENSE

; AppMutex: created by the running app (see src/rebind/app.py's main()) so Setup can detect an
; already-running instance and offer to close it automatically before overwriting its files --
; the point being a plain re-run of this installer over an existing install upgrades in place
; (same AppId => Inno Setup recognizes it), with no manual uninstall/quit step required first.
AppMutex=RebindSingleInstanceMutex

[Files]
Source: "dist\rebind\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\LICENSE"; DestDir: "{app}\licenses"; DestName: "LICENSE-Rebind.txt"; Flags: ignoreversion

[Icons]
; IconFilename/IconIndex are set explicitly (not just inherited from the exe) so a pinned taskbar
; shortcut resolves the icon unambiguously even when Windows' icon cache holds a stale entry from a
; previous, icon-less install at the same path.
Name: "{group}\Rebind"; Filename: "{app}\rebind.exe"; IconFilename: "{app}\rebind.exe"; IconIndex: 0
Name: "{autodesktop}\Rebind"; Filename: "{app}\rebind.exe"; IconFilename: "{app}\rebind.exe"; IconIndex: 0

[Run]
Filename: "{app}\rebind.exe"; Description: "Start Rebind"; Flags: nowait postinstall skipifsilent
