[Setup]
; Fixed, stable GUID identifying "Rebind" across all versions -- Inno Setup uses AppId (not
; AppName) to recognize an existing install for upgrade/uninstall purposes. Without an
; explicit AppId, Inno Setup derives one from AppName, which is fragile (a rename would orphan
; every existing install); generated once with `uv run python -c "import uuid; print(uuid.uuid4())"`
; and must never change between releases.
AppId={{11732952-84C2-467D-9E8D-5263D9A81C11}
AppName=Rebind
AppVersion=0.3.0
AppPublisher=Thomas Scharff
DefaultDirName={autopf}\Rebind
DefaultGroupName=Rebind
OutputBaseFilename=rebind-setup
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
; The bundle vendors third-party components under LGPL-2.1/LGPL-3/MIT/FTL/Apache-2.0/etc -- the
; trimmed GTK DLL set plus the frozen Python dependency closure (the OCR engine, onnxruntime,
; opencv, pypdfium2, numpy, ...) and the bundled OCR models. The installer is the point of
; distribution where those obligations must be discharged. LicenseFile shows this text in the
; setup wizard before install proceeds; the [Files] entry below additionally ships the full
; notices into the installed payload so they remain available after installation, not just during
; it. LICENSE-THIRD-PARTY.txt and PYTHON-INVENTORY.md are generated by
; scripts/license_inventory.py, which fails if any bundled Python distribution has no license
; text -- so changing what the bundle vendors cannot silently invalidate what this claims.
LicenseFile=licenses\LICENSE-THIRD-PARTY.txt

[Files]
Source: "dist\rebind\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\LICENSE"; DestDir: "{app}\licenses"; DestName: "LICENSE-Rebind.txt"; Flags: ignoreversion

[Icons]
; IconFilename/IconIndex are set explicitly (not just inherited from the exe) so a pinned taskbar
; shortcut resolves the icon unambiguously even when Windows' icon cache holds a stale entry from a
; previous, icon-less install at the same path.
Name: "{group}\Rebind"; Filename: "{app}\rebind.exe"; IconFilename: "{app}\rebind.exe"; IconIndex: 0
Name: "{autodesktop}\Rebind"; Filename: "{app}\rebind.exe"; IconFilename: "{app}\rebind.exe"; IconIndex: 0

[Run]
Filename: "{app}\rebind.exe"; Description: "Start Rebind"; Flags: nowait postinstall skipifsilent
